@host = http://127.0.0.1:5000

### Create new customers
POST {{host}}/customers
Content-Type: application/json

{
    "custFname": "fdgdfgdgdgf",
    "custLname": "Rasdasdasdadas",
    "isMember": "1"
}


### Get the list of all the customers
GET {{host}}/customers
Content-Type: application/json

### Get a single customer by ID
GET {{host}}/customers/1
Content-Type: application/json

### Update a customer
PUT {{host}}/customers/1
Content-Type: application/json

{
    "custFname": "Joahnna Mae",
    "custLname": "Bas",
    "isMember": "1"
}

### Delete a customer
DELETE {{host}}/customers/8
Content-Type: application/json