
@host = http://127.0.0.1:5000

### Create a new item
POST {{host}}/items
Content-Type: application/json

{
    "itemName": "ItemC",
    "itemQuantity": "31",
    "itemPrice": "9.10"
}

### Get the list of all the items
GET {{host}}/items
Content-Type: application/json

### Get a single item by ID
GET {{host}}/items/1
Content-Type: application/json

### Update an item
PUT {{host}}/items/2
Content-Type: application/json

{
    "itemName": "ItemB",
    "itemQuantity": "50",
    "itemPrice": "13.55"
}

### Delete an item
DELETE {{host}}/items/6
Content-Type: application/json